//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2025.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2025.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2
        ///R6
        ///L19
        ///L50
        ///L44
        ///R50
        ///R48
        ///L35
        ///R5
        ///R11
        ///R15
        ///R47
        ///R29
        ///R6
        ///R33
        ///R43
        ///R25
        ///R42
        ///L34
        ///R22
        ///L4
        ///L35
        ///R4
        ///R28
        ///R29
        ///L8
        ///L14
        ///L25
        ///R9
        ///L37
        ///L42
        ///R26
        ///R27
        ///R47
        ///L21
        ///R31
        ///L9
        ///L6
        ///R26
        ///R44
        ///R2
        ///L38
        ///L14
        ///R21
        ///R49
        ///L47
        ///R23
        ///L25
        ///R20
        ///L13
        ///R12
        ///L46
        ///L66
        ///R12
        ///L41
        ///L92
        ///R19
        ///L89
        ///R30
        ///L39
        ///L30
        ///L24
        ///R13
        ///R75
        ///L92
        ///R58
        ///R68
        ///R32
        ///R12
        ///L33
        ///R49
        ///L28
        ///R41
        ///R24
        ///R76
        ///L62
        ///R14
        ///L93
        ///R25
        ///R75
        ///R68
        ///L19
        ///L49
        ///R13
        ///R71
        ///R16
        ///L4
        ///L40
        ///R31
        ///L75
        ///L90
        ///L40
        ///L82
        ///R63
        ///L99
        ///L56
        ///R17
        ///R40
        ///R94
        ///L59
        ///R12
        ///L3
        ///R91
        ///R66
        ///R34
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12077-25471,4343258-4520548,53-81,43661-93348,6077-11830,2121124544-2121279534,631383-666113,5204516-5270916,411268-591930,783-1147,7575717634-7575795422,8613757494-8613800013,4-19,573518173-573624458,134794-312366,18345305-18402485,109442-132958,59361146-59451093,1171-2793,736409-927243,27424-41933,93-216,22119318-22282041,2854-4778,318142-398442,9477235089-9477417488,679497-734823,28-49,968753-1053291,267179606-267355722,326-780,1533294120-1533349219
        ///.
        /// </summary>
        internal static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
    }
}
